version: '3.8'

services:
  backend:
    container_name: attendance-backend
    build: ./Backend
    ports:
      - "3208:3208"
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=attendance_db

  employee-attendance:
    container_name: employee-attendance
    build: ./Employee-attendance
    ports:
      - "8015:80"
    depends_on:
      - backend

  hr-attendance:
    container_name: hr-attendance
    build: ./HR-attendance
    ports:
      - "8016:80"
    depends_on:
      - backend

  postgres:
    container_name: postgres-attendance
    image: postgres:13
    ports:
      - "5208:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=attendance_db
    volumes:
      - attendance_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  attendance_pgdata:

